services:
  web:
    build: .
    container_name: hashzeugui
    ports:
      - "8132:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped