services:
  hashzeugui:
    image: tiritibambix/hashzeugui:latest
    container_name: hashzeugui
    ports:
      - "8132:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped